## Automations for IFTTT

# Record speedtests
- alias: 'ifttt_Speed test record'
  trigger:
    platform: state
    entity_id: sensor.speedtest_upload
  action:
    - delay:
        seconds: 30
    - service: ifttt.trigger
      data_template:
        event: 'HA_speedtest_trigger'
        value1: '{{ states("sensor.speedtest_download") }}'
        value2: '{{ states("sensor.speedtest_upload") }}'
        value3: '{{ states("sensor.speedtest_ping") }}'