## Automations for when I'm Away 

- alias: 'loc-away_Devices off when away'
  trigger:
    platform: state
    entity_id: input_select.ron_status
    state: "Away"
  condition:
    condition: state
    entity_id: input_boolean.friend_visiting
    state: "off"
  action:
    service: homeassistant.turn_off
    entity_id: group.living_room, group.bedroom

- alias: 'loc-away_Devices in bedroom off when at the computer'
  trigger:
    platform: state
    entity_id: input_select.ron_status
    state: "Using Computer"
  condition:
    condition: state
    entity_id: input_boolean.friend_visiting
    state: "off"
  action:
    service: homeassistant.turn_off
    entity_id: group.bedroom

- alias: 'loc-away_Devices on desk off when leave the computer'
  trigger:
    platform: state
    entity_id: input_select.ron_status
    from: "Using Computer"
  action:
    service: homeassistant.turn_off
    entity_id: switch.amp