## Living room automations

- alias: 'rm-lv_Amp off at 3 AM'
  trigger:
    platform: time
    after: '03:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.amp

# Turn off amp with Humvee computer
- alias: 'rm-lv_Amp off with Humvee'
  trigger:
    platform: state
    entity_id: device_tracker.humvee
    from: 'home'
    to: 'not_home'
    for:
      minutes: 1
  action:
    service: homeassistant.turn_off
    entity_id: switch.amp