## Vacation Mode
# Inspired by geek of week
# https://github.com/geekofweek/homeassistant

# Turn vacation mode on automatically
- alias: 'stat-vac_Vacation mode on when gone 24 hours'
  trigger:
    - platform: state
      entity_id: device_tracker.ron_phone
      from: 'home'
      to: 'not_home'
      for:
        hours: 24
        minutes: 0
        seconds: 0
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.vacation_mode

# Turn vacation mode off automatically
- alias: 'stat-vac_Vacation mode off when home'
  trigger:
    - platform: state
      entity_id: device_tracker.ron_phone 
      from: 'not_home'
      to: 'home'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.vacation_mode

# Turn on lights when vacation mode active
- alias: 'stat-vac_Vacation lights at sunset when vacation mode on'
  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'above_horizon'
      to: 'below_horizon'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
  action:
    - service: script.vacation_lights