##########################################
##### Switch
##########################################

- platform: rpi_rf
  gpio: 17
  switches:
    # switch1:
    amp:
      protocol: 1
      pulselength: 186
      code_on: !secret code1_on
      code_off: !secret code1_off
    # switch2:
    bedroom_fan:
      protocol: 1
      pulselength: 186
      code_on: !secret code2_on
      code_off: !secret code2_off
    # switch3:
    bedroom_nightstand:
      protocol: 1
      pulselength: 186
      code_on: !secret code3_on
      code_off: !secret code3_off
    switch4:
      protocol: 1
      pulselength: 186
      code_on: !secret code4_on
      code_off: !secret code4_off
    switch5:
      protocol: 1
      pulselength: 186
      code_on: !secret code5_on
      code_off: !secret code5_off